# Generated by Django 5.2.3 on 2025-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ton_wallet',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
