# Generated by Django 5.2.3 on 2026-01-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tonprocessedtx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
