# Generated by Django 5.2.3 on 2026-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_branches_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
