# Generated by Django 5.2.3 on 2025-06-15 19:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('duration_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CF', 'FLORA'), ('TON', 'TON-Дерево')], default='CF', max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('income_per_hour', models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10)),
                ('branches_collected', models.PositiveIntegerField(default=0)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('fertilized_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_water_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='users.user')),
            ],
        ),
    ]
