# Generated by Django 5.2.3 on 2025-06-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='last_cf_accrued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
