# Generated by Django 5.2.3 on 2025-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_tree_last_cf_accrued'),
    ]

    operations = [
        migrations.AddField(
            model_name='tondistribution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
