# Generated by Django 5.2.3 on 2025-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_tondistribution_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tondistribution',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='tondistribution',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='tondistribution',
            name='distributed_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
