# Generated by Django 5.2.3 on 2025-07-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_remove_tondistribution_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='last_collected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
