# Generated by Django 5.2.3 on 2026-01-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_burnedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='water_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
