# Generated by Django 5.2.3 on 2026-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_tree_water_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tondistribution',
            options={'verbose_name': 'Раздача TON', 'verbose_name_plural': 'Раздачи TON'},
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='distributed_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Распределено TON'),
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='tondistribution',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Всего TON'),
        ),
    ]
