# Generated by Django 5.2.3 on 2026-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_alter_tondistribution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(choices=[('CF', 'FLORA'), ('TON', 'TON')], default='CF', max_length=20),
        ),
    ]
