# Generated by Django 5.1.1 on 2025-06-16 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('burn', 'Сжигание'), ('mint', 'Выпуск'), ('ton_distribution', 'Распределение TON')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Операция с токенами',
                'verbose_name_plural': 'Операции с токенами',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TokenSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_total_supply', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Общее количество токенов',
                'verbose_name_plural': 'Общее количество токенов',
            },
        ),
    ]
