# Generated by Django 5.2.3 on 2025-06-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
