# Generated by Django 5.2.3 on 2025-07-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_pricehistory'),
        ('users', '0003_tonprocessedtx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='token_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='action',
            field=models.CharField(choices=[('buy', 'Купить CF'), ('sell', 'Продать CF')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cf_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_orders', to='users.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ton_to_rub',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
