# Generated by Django 5.2.3 on 2025-07-14 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_remove_transaction_buyer_remove_transaction_order_and_more'),
        ('users', '0003_tonprocessedtx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.CharField(choices=[('buy', 'Купить CF за TON'), ('sell', 'Продать CF за TON')], max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='cf_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='ton_to_rub',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
