# Generated by Django 5.2.3 on 2025-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0004_alter_order_action_alter_order_cf_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
