# Generated by Django 5.2.3 on 2025-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0005_alter_pricehistory_options_alter_pricehistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_market_open', models.BooleanField(default=True)),
            ],
        ),
    ]
