# Generated by Django 5.2 on 2025-04-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderCancelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_log', to='farm.order')),
            ],
        ),
    ]
