# Generated by Django 5.2 on 2025-04-17 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_user_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TON', 'TON‑tree'), ('NOT', 'NOT‑tree')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='ordercancellog',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=8, editable=False, max_digits=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='farm_order_status_279e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='farm_order_order_t_c4985e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expires_at'], name='farm_order_expires_3f8fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['owner'], name='farm_tree_owner_i_d8c9e4_idx'),
        ),
        migrations.AddField(
            model_name='specialtree',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='specialtree',
            unique_together={('owner', 'kind')},
        ),
    ]
