# Generated by Django 5.2 on 2025-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_specialtree_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtree',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialtree',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
