# Generated by Django 5.2 on 2025-04-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0007_adslot_adpurchase_donation"),
    ]

    operations = [
        migrations.CreateModel(
            name="P2POrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_cf", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "fixed_price_ton",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "current_market_price_ton",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p2p_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="P2POrderCancelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cancelled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=8, editable=False, max_digits=20
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancel_log",
                        to="farm.p2porder",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="p2porder",
            index=models.Index(fields=["status"], name="farm_p2pord_status_261e39_idx"),
        ),
        migrations.AddIndex(
            model_name="p2porder",
            index=models.Index(
                fields=["expires_at"], name="farm_p2pord_expires_7889a2_idx"
            ),
        ),
    ]
