# Generated by Django 5.2 on 2025-04-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0009_user_auth_date_user_photo_url_alter_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_earnings",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="user",
            name="referrals_count",
            field=models.IntegerField(default=0),
        ),
    ]
