# Generated by Django 5.2 on 2025-04-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0010_user_referral_earnings_user_referrals_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="referral_earnings",
        ),
        migrations.RemoveField(
            model_name="user",
            name="referrals_count",
        ),
    ]
