# Generated by Django 5.2 on 2025-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0011_remove_user_referral_earnings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_earnings",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="user",
            name="referrals_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
