# Generated by Django 5.2 on 2025-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0012_user_referral_earnings_user_referrals_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
