# Generated by Django 5.2 on 2025-05-01 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0013_transaction_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("water_24", "Автополив 24ч"),
                            ("water_48", "Автополив 48ч"),
                            ("fertilizer", "Удобрение X2"),
                            ("branches", "Ветки"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("price_ton", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Длительность действия предмета в часах (для временных эффектов)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "total_price_ton",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ton_transaction_hash",
                    models.CharField(
                        blank=True,
                        help_text="Хеш транзакции в блокчейне TON",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("failed", "Не удалось"),
                            ("completed", "Использовано"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="farm.shopitem",
                    ),
                ),
            ],
        ),
    ]
