# Generated by Django 5.2 on 2025-05-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0014_shopitem_itempurchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itempurchase",
            name="item",
        ),
        migrations.RemoveField(
            model_name="itempurchase",
            name="user",
        ),
        migrations.DeleteModel(
            name="ShopItem",
        ),
        migrations.DeleteModel(
            name="ItemPurchase",
        ),
    ]
