# Generated by Django 5.2 on 2025-05-13 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_remove_itempurchase_item_remove_itempurchase_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_income_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('image_level_1', models.CharField(default='tree1.png', max_length=255)),
                ('image_level_2', models.CharField(default='tree2.png', max_length=255)),
                ('image_level_3', models.CharField(default='tree3.png', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreePurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_purchases', to=settings.AUTH_USER_MODEL)),
                ('tree_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.treetype')),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='farm.treetype'),
        ),
    ]
