# Generated by Django 5.2 on 2025-05-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_create_default_tree_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treetype',
            name='hourly_income_multiplier',
        ),
        migrations.AddField(
            model_name='treetype',
            name='hourly_income',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='treetype',
            name='income_currency',
            field=models.CharField(choices=[('CF', 'CryptoFlora'), ('TON', 'Toncoin')], default='CF', max_length=3),
        ),
        migrations.AlterField(
            model_name='treetype',
            name='price_ton',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
