# Generated by Django 5.2 on 2025-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_create_default_trees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='waterlog',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='currency',
            field=models.CharField(choices=[('CF', 'CryptoFlora'), ('TON', 'Toncoin')], default='CF', max_length=3),
        ),
    ]
