# Generated by Django 5.1.7 on 2025-12-08 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_tonprocessedtx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=15)),
                ('used_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Пул ботов',
                'verbose_name_plural': 'Пулы ботов',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершен'), ('rewarded', 'Награды выданы')], default='active', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('reward_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GameQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_queues', to='users.user')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rps.tournament')),
            ],
            options={
                'verbose_name': 'Очередь игры',
                'verbose_name_plural': 'Очереди игр',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('pvp', 'Игрок vs Игрок'), ('pve', 'Игрок vs Бот')], default='pvp', max_length=3)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('betting', 'Выбор ставки'), ('playing', 'Игра идет'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=10)),
                ('is_bot_game', models.BooleanField(default=False)),
                ('bot_balance', models.DecimalField(decimal_places=2, default=1000, max_digits=15)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('player1_bet', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('player2_bet', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('game_bank', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('player1_move', models.CharField(blank=True, max_length=10, null=True)),
                ('player2_move', models.CharField(blank=True, max_length=10, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('move_timer_start', models.DateTimeField(blank=True, null=True)),
                ('search_timer_start', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='users.user')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player2', to='users.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='users.user')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rps.tournament')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('coins_won', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('coins_lost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reward_received', models.BooleanField(default=False)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rps.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='users.user')),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турниров',
                'ordering': ['-points', 'games_played'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
