# Generated by Django 5.1.7 on 2025-12-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
