# Generated by Django 5.1.7 on 2025-12-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0002_game_expires_at'),
        ('users', '0003_tonprocessedtx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_admins', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_admin', to='users.user')),
            ],
            options={
                'verbose_name': 'Администратор бота',
                'verbose_name_plural': 'Администраторы бота',
                'ordering': ['-added_at'],
            },
        ),
    ]
