# Generated by Django 5.1.7 on 2026-01-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0003_botadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bot_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
